#+title: Experiments in Quint ML

This repo holds some experiments focused on or around [[https://github.com/informalsystems/quint][quint]] and conducted in the
MLs [[https://en.wikipedia.org/wiki/OCaml][OCaml]] and [[https://www.fstar-lang.org/][F*]].

Everything in here is very rough and a WIP.

* Contents Worth Remarking

- [[./tryf/]] :: An EDSL aiming to capture the pure and action fragments of quint in F*.
  - See the example in [[./tryf/Quint.Ex.TicTacToe.fst]] for an example of how this
    EDSL can be used.
- [[./bin/main.ml]] :: Entrypoint for a CLI that runs the
  [[./tryf/Quint.Ex.TicTacToe.fst]] example. This shows how we can integrate the
  code compiled from F* with normal ocaml code.
- [[./test/quint-ml-demo.t]] :: Blackbox CLI tests showing invocation of the CLI.
- [[./notes.org]] :: Working notes on the project
- [[./bin/ocaml_ttt_ex_main.ml]] :: A sketch of an OCaml approach to a toy quint
  spec. This was a prelude to the F* code.

* Building for development

Assuming you have [[https://opam.ocaml.org/doc/Install.html][opam]] installed:

** Install dependencies

#+begin_src
git clone git@github.com:informalsystems/quint-ml-experiments.git
cd quint-ml-experiments
opam switch create . --locked
#+end_src

** Build

#+begin_src
dune build
#+end_src

** Test

#+begin_src
dune test
#+end_src

** Run the demo simulation

#+begin_src
dune exec quint-ml-demo
#+end_src

See [[file:test/quint-ml-demo.t][the integration tests]] for more usage examples.
